global:
  proxy:
    autoInject: enabled
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  istioNamespace: istio-system

meshConfig:
  accessLogFile: /dev/stdout
  enablePrometheusMerge: true
  defaultConfig:
    proxyMetadata:
      ISTIO_META_ENABLE_IPV6: "false"
  defaultServiceExportTo:
    - "*"
  defaultDestinationRuleExportTo:
    - "*"

pilot:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi