# helm/istio/gateway/values.onprem.yaml

service:
  type: NodePort
  ports:
    - name: http2
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 30443

    # ✅ Envoy metrics 수집용 포트 추가!
    - name: http-envoy-prom
      port: 15090
      targetPort: 15090
      protocol: TCP