apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxy
  namespace: istio-system
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
      - key: istio-prometheus-ignore
        operator: NotIn
        values: ["true"]
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /stats/prometheus
      port: http-envoy-prom
      interval: 15s