# file: 01-loki-shared-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-shared-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 20Gi