# manifests/apps/09-promtail.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: infra
  source:
    repoURL: https://grafana.github.io/helm-charts  # Helm repo!
    chart: promtail                                 # chart name
    targetRevision: 6.15.3                          # chart version
    helm:
      values: |
        config:
          clients:
            - url:  http://loki-loki-distributed-gateway.monitoring.svc.cluster.local/loki/api/v1/push
          snippets:
            pipeline_stages:
              - docker: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true