# manifests/apps/09-promtail.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: infra
  source:
    repoURL: https://grafana.github.io/helm-charts  # Helm repo!
    chart: promtail                                 # chart name
    targetRevision: 6.15.3                          # chart version
    helm:
      values: |
        config:
          clients:
            - url:  http://loki-loki-distributed-gateway.monitoring.svc.cluster.local
          snippets:
            pipeline_stages:
              - docker: {}

          scrape_configs:
            - job_name: kubernetes-pods
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: kubernetes-pods
                    __path__: /var/log/pods/*/*/*.log
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  target_label: app
                - source_labels: [__meta_kubernetes_namespace]
                  target_label: namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  target_label: pod
                - source_labels: [__meta_kubernetes_container_name]
                  target_label: container

        extraVolumes:
          - name: pod-logs
            hostPath:
              path: /var/log/pods
              type: Directory

        extraVolumeMounts:
          - name: pod-logs
            mountPath: /var/log/pods
            readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true