apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: infra
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-distributed
    targetRevision: 0.74.0
    helm:
      values: |
        singleBinary:
          replicas: 1

        loki:
          auth_enabled: false
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  prefix: index_
                  period: 24h

        backend:
          enabled: true
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: nfs-storage

        ingester:
          persistence:
            enabled: true
            size: 10Gi
            storageClassName: nfs-storage

        compactor:
          enabled: true
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: nfs-storage

        distributor:
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: nfs-storage

        querier:
          replicas: 1
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: nfs-storage

        queryFrontend:
          replicas: 1
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: nfs-storage

        read:
          replicas: 1

        write:
          replicas: 1

        gateway:
          enabled: true

        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true