- name: Install NFS client
  apt:
    name: nfs-common
    state: present
    update_cache: true

- name: Create mount point
  file:
    path: /mnt
    state: directory

- name: Mount NFS
  mount:
    path: /mnt
    src: 192.168.56.100:/mnt/nfs-storage
    fstype: nfs
    opts: defaults
    state: mounted