# manifests/apps/07-monitoring/07-03-metrics-server.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: metrics-server
    targetRevision: 6.11.4
    helm:
      values: |
        apiService:
          create: true
        args:
          - --kubelet-insecure-tls=true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true