apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: infra
  source:
    repoURL: https://github.com/seokmingg/hybrid-cloud
    targetRevision: main
    path: manifests/istio
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true