cni:
  enabled: true
  chained: true
  cniConfDir: /etc/cni/net.d
  cniConfFileName: 10-calico.conflist  # ✅ 반드시 명시
  cniBinDir: /opt/cni/bin
  logLevel: info
  excludeNamespaces:
    - kube-system
    - istio-system

global:
  istioNamespace: istio-system