cni:
  enabled: true
  cniConfFileName: 05-istio-cni.conf
  cniBinDir: /opt/cni/bin
  cniConfDir: /etc/cni/net.d
  chained: true
  logLevel: info
  excludeNamespaces:
    - istio-system
    - kube-system
  namespace: kube-system

global:
  istioNamespace: istio-system