# ------------------------------------------------------------
# 1. APT 캐시 업데이트 및 필수 패키지 설치
# ------------------------------------------------------------

- name: APT 캐시 초기화
  apt:
    update_cache: yes

- name: 필수 패키지 설치
  apt:
    name:
      - apt-transport-https   # HTTPS 지원 APT transport
      - ca-certificates       # 인증서 관리
      - curl                  # URL 요청 도구
      - gnupg                 # GPG 키 처리
      - lsb-release           # 배포판 정보 확인용
      - chrony                # 시간 동기화 서비스
      - unzip                 # 압축 해제 유틸
      - vim                   # 텍스트 편집기
      - net-tools             # ifconfig 등 네트워크 도구
      - iputils-ping          # ping 명령어
      - jq                    # JSON 파싱 도구
      - htop                  # 프로세스 모니터링
      - bash-completion       # CLI 자동완성
    state: present

- name: chrony 시간 동기화 서비스 시작
  systemd:
    name: chrony
    enabled: true
    state: started

# ------------------------------------------------------------
# 2. Swap 비활성화
# ------------------------------------------------------------

- name: Swap 비활성화
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: /etc/fstab에서 swap 주석 처리
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s)'
    replace: '#\1'

# ------------------------------------------------------------
# 3. 커널 모듈 및 파라미터 설정
# ------------------------------------------------------------

- name: 커널 모듈 설정 파일 생성
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: 커널 모듈 로드
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: 커널 파라미터 설정
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: 커널 파라미터 적용
  command: sysctl --system