{{- if .Values.global.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-hybrid-vs
  namespace: test
spec:
  hosts:
    - {{ .Values.global.domain }}
  gateways:
    - {{ .Values.global.istio.gateway }}
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 308
    - match:
        - uri:
            prefix: "/api"
      corsPolicy:
        allowOrigins:
          - exact: "https://{{ .Values.global.domain }}"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
        maxAge: "24h"
      route:
        - destination:
            host: test-hybrid-back.test.svc.cluster.local
            port:
              number: 3000
    - route:
        - destination:
            host: test-hybrid-front.test.svc.cluster.local
            port:
              number: 80
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: test
spec:
  selector:
    matchLabels:
      app: test-hybrid-back
  jwtRules:
    - issuer: "https://{{ .Values.global.domain }}"
      jwksUri: "https://{{ .Values.global.domain }}/.well-known/jwks.json"
      forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: test
spec:
  selector:
    matchLabels:
      app: test-hybrid-back
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            methods: ["POST"]
            paths: ["/api/chat"]
{{- end }} 