{{- if .Values.global.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: test-hybrid-cors
  namespace: test
spec:
  selector:
    matchLabels:
      app: test-hybrid-back
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
---
apiVersion: networking.istio.io/v1beta1
kind: EnvoyFilter
metadata:
  name: test-hybrid-cors
  namespace: test
spec:
  workloadSelector:
    labels:
      app: test-hybrid-back
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors"
            allow_origin_string_match:
              - prefix: "https://"
            allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
            allow_headers: "Authorization,Content-Type"
            expose_headers: "Authorization"
            max_age: "86400"
{{- end }} 