postgresql-ha:
  enabled: true
  postgresql:
    existingSecret: test-hybrid-db-secrets
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    podLabels:
      sidecar.istio.io/inject: "false"
  haproxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    podLabels:
      sidecar.istio.io/inject: "false"
  pgpool:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    podLabels:
      sidecar.istio.io/inject: "false"
  persistence:
    enabled: true
    storageClass: nfs-storage
    size: 5Gi
  nodeSelector: {}
  tolerations: []