# manifests/services/nginx-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "99"
spec:
  project: default
  source:
    repoURL: https://github.com/seokmingg/hybrid-cloud
    targetRevision: main
    path: helm/gitops-test/nginx
    helm:
      releaseName: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true