apiVersion: kustomize.config.k8s.io/v1beta2  # 꼭 v1beta2로
kind: Kustomization

helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    releaseName: promtail
    namespace: monitoring
    version: 6.15.3
    valuesFile: values.yaml