apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-shared
  namespace: monitoring
  labels:
    app: loki-shared-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-storage