apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: Infrastructure management project
  sourceRepos:
    - https://github.com/seokmingg/hybrid-cloud
    - https://charts.external-secrets.io
    - https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    - https://charts.jetstack.io # cert-manager
    - https://prometheus-community.github.io/helm-charts
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://github.com/prometheus-community/helm-charts
    - https://github.com/prometheus-operator/prometheus-operator
    - https://metallb.github.io/metallb
    - https://grafana.github.io/helm-charts


  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'