apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-config
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  alerting.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: cpu
        folder: system
        interval: 1m
        rules:
          - uid: aei0b86ch9ts0b
            title: node_cpu_seconds_total
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: fehyowlpd8ruof
                model:
                  disableTextWrap: false
                  editorMode: builder
                  expr: instance:node_cpu:ratio
                  fullMetaSearch: false
                  includeNullMetadata: true
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
                  useBackend: false
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 0.9
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 1m
            annotations:
              description: CPU 사용률이 90% 초과 시 알림 발생
              summary: 노드CPU사용률{{ $labels.instance }}
            isPaused: false
            notification_settings:
              receiver: slack
      - orgId: 1
        name: disk
        folder: system
        interval: 1m
        rules:
          - uid: fei0i280ln8jka
            title: master-node-filesystem /
            condition: D
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: fehyowlpd8ruof
                model:
                  disableTextWrap: false
                  editorMode: builder
                  expr: node_filesystem_size_bytes{fstype!~"tmpfs|overlay", instance="192.168.0.100:9100", mountpoint="/", device="/dev/mapper/ubuntu--vg-ubuntu--lv"}
                  fullMetaSearch: false
                  includeNullMetadata: true
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
                  useBackend: false
              - refId: B
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: fehyowlpd8ruof
                model:
                  datasource:
                    type: prometheus
                    uid: fehyowlpd8ruof
                  disableTextWrap: false
                  editorMode: builder
                  expr: node_filesystem_avail_bytes{fstype!~"tmpfs|overlay", instance="192.168.0.100:9100", mountpoint="/", device="/dev/mapper/ubuntu--vg-ubuntu--lv"}
                  fullMetaSearch: false
                  includeNullMetadata: true
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: B
                  useBackend: false
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 0
                          - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                  datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                  expression: 100*($A-$B)/$A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: math
              - refId: D
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 90
                          - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                  datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                  expression: C
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: D
                  type: threshold
            noDataState: NoData
            execErrState: Error
            annotations:
              description: 사용률 90%초과
              summary: '디스크 사용률 경고: {{ $labels.instance }} ({{ $labels.mountpoint }})'
            isPaused: false
            notification_settings:
              receiver: slack
      - orgId: 1
        name: memory
        folder: system
        interval: 1m
        rules:
          - uid: bei0blr52hclcf
            title: node-memory
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: fehyowlpd8ruof
                model:
                  disableTextWrap: false
                  editorMode: builder
                  expr: instance:node_memory_utilisation:ratio
                  fullMetaSearch: false
                  includeNullMetadata: true
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
                  useBackend: false
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 0.95
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 1m
            annotations:
              description: 메모리95%넘어가면알람
              summary: 노드메모리사용률{{ $labels.instance }}
            isPaused: false
            notification_settings:
              receiver: slack
