# manifests/monitoring/servicemonitor-istio.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-proxies
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: istio-ingressgateway   # ✅ 이거!
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s