# manifests/apps/06-harbor.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: infra
  source:
    repoURL: https://github.com/seokmingg/hybrid-cloud
    targetRevision: main
    path: helm/harbor
    helm:
      valueFiles:
        - values.onprem.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true