- name: seokmin 사용자 생성 (이미 있으면 skip)
  user:
    name: seokmin
    groups: sudo
    shell: /bin/bash
    state: present
    create_home: yes

- name: seokmin 사용자에 docker 그룹 추가
  user:
    name: seokmin
    groups: docker
    append: yes

- name: seokmin 사용자에 비밀번호 없는 sudo 권한 부여
  copy:
    dest: /etc/sudoers.d/seokmin
    content: "seokmin ALL=(ALL) NOPASSWD:ALL\n"
    mode: '0440'