{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: test-hybrid-front
  namespace: test
spec:
  selector:
    app: test-hybrid-front
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}