apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: route53-credentials-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: route53-credentials-secret
    creationPolicy: Owner
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: /cert-manager/aws_access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: /cert-manager/aws_secret_access_key