# manifests/external-secrets/github-test-hybrid-pat-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-pat
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store    # ✅ 이걸로 수정!
    kind: ClusterSecretStore
  target:
    name: github-pat
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /secrets/github/test-hybrid-pat