# manifests/external-secrets/github-test-hybrid-pat-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-pat
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: github-pat
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: https://github.com/seokmingg/test-hybrid
        username: seokmingg
        password: "{{ .password }}"
        type: git
  data:
    - secretKey: password
      remoteRef:
        key: /secrets/github/test-hybrid-pat