apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-pat-secret
  namespace: argocd
spec:
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: github-pat
  data:
    - secretKey: password
      remoteRef:
        key: /secrets/github/test-hybrid-pat