apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: harbor-admin
    creationPolicy: Owner
  data:
    - secretKey: harbor-admin-password
      remoteRef:
        key: /harbor/admin-password