apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-hybrid-back-secrets
  namespace: test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: test-hybrid-back-secrets  # ✅ 생성될 Kubernetes Secret 이름도 동일
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /test/jwt-secret
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: /test/google-client-id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: /test/google-client-secret
    - secretKey: KAKAO_CLIENT_ID
      remoteRef:
        key: /test/kakao-client-id
    - secretKey: KAKAO_CLIENT_SECRET
      remoteRef:
        key: /test/kakao-client-secret
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: /test/postgres-username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /test/postgres-password
    - secretKey: POSTGRES_DBNAME
      remoteRef:
        key: /test/postgres-dbname
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: /test/postgres-host