apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-hybrid-db-secrets
  namespace: test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: test-hybrid-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: /test/postgres-username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /test/postgres-password
    - secretKey: POSTGRES_DBNAME
      remoteRef:
        key: /test/postgres-dbname