apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-hybrid-db-secrets
  namespace: test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: test-hybrid-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRESQL_USERNAME
      remoteRef:
        key: /test/POSTGRESQL_USERNAME
    - secretKey: POSTGRESQL_PASSWORD
      remoteRef:
        key: /test/POSTGRESQL_PASSWORD
    - secretKey: POSTGRESQL_DATABASE
      remoteRef:
        key: /test/POSTGRESQL_DATABASE