apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-hybrid-db-secrets
  namespace: test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: test-hybrid-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgresql-username
      remoteRef:
        key: /test/POSTGRESQL_USERNAME
    - secretKey: postgresql-password
      remoteRef:
        key: /test/POSTGRESQL_PASSWORD
    - secretKey: postgresql-database
      remoteRef:
        key: /test/POSTGRESQL_DATABASE
    - secretKey: postgresql-replication-password
      remoteRef:
        key: /test/POSTGRESQL_PASSWORD