- name: Docker 설치를 위한 필수 패키지 설치
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - git
      - make
      - gcc
      - pkg-config
      - libseccomp-dev
      - golang-go
    state: present
    update_cache: true

- name: Docker GPG 키 추가
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker 저장소 추가
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Docker 설치
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Docker 시작 및 부팅 시 자동 실행
  systemd:
    name: docker
    enabled: true
    state: started

- name: cri-dockerd 설치 (clone & build)
  shell: |
    cd /usr/local/src
    git clone https://github.com/Mirantis/cri-dockerd.git
    cd cri-dockerd
    mkdir -p bin
    go build -o bin/cri-dockerd
    cp -a packaging/systemd/* /etc/systemd/system
    cp bin/cri-dockerd /usr/bin/cri-dockerd
    sed -i 's:/usr/bin/cri-dockerd:/usr/bin/cri-dockerd:' /etc/systemd/system/cri-docker.service
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

- name: systemd 리로드 및 cri-docker 서비스 시작
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    daemon_reload: true
  loop:
    - cri-docker.socket
    - cri-docker.service