apiVersion: kustomize.config.k8s.io/v1beta2  # 꼭 v1beta2로
kind: Kustomization

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: monitoring
    version: 5.41.4
    valuesFile: values.yaml