# roles/worker-join-role/tasks/main.yaml
- name: 마스터에서 join 커맨드 문자열 가져오기
  shell: kubeadm token create --print-join-command
  register: join_cmd
  delegate_to: onprem-master
  run_once: true
  become: true
  tags: join

- name: 워커에서 join 커맨드 실행
  command: "{{ join_cmd.stdout }} --cri-socket=unix:///var/run/cri-dockerd.sock"