# hybrid-cloud/helm/argocd/values.onprem.yaml
global:
  domain: argocdt.seokmin.com

server:
  ingress:
    enabled: false

configs:
  params:
    server.insecure: true

  secret:
    createSecret: true

  cm:
    accounts.user: login

  rbac:
    policy.csv: |
      p, role:readonly, applications, get, *, allow
      p, role:readonly, projects, get, *, allow
      p, role:readonly, clusters, get, *, allow
      p, role:readonly, repositories, get, *, allow
      g, user, role:readonly




repoServer:
  autoscaling:
    enabled: false

controller:
  replicas: 1

redis:
  enabled: true

dex:
  enabled: false