# hybrid-cloud/helm/argocd/values.onprem.yaml
global:
  domain: argocdt.seokmin.com

server:
  ingress:
    enabled: false

configs:
  params:
    server.insecure: true

  secret:
    createSecret: true


repoServer:
  autoscaling:
    enabled: false

controller:
  replicas: 1

redis:
  enabled: true

dex:
  enabled: false