apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-service-test-hybrid
  namespace: argocd
spec:
  project: service-app
  source:
    repoURL: https://github.com/seokmingg/hybrid-cloud
    targetRevision: main
    path: manifests/service-apps/test-hybrid
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true