apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-cronjob
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/seokmingg/hybrid-cloud
    targetRevision: main
    path: manifests/cronjobs  # CronJob들만 따로 모아놓은 폴더
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: job
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true 