---
# roles/master-init-role/tasks/main.yaml
- name: kubeadm init 실행
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///var/run/cri-dockerd.sock
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf

- name: kubeadm init 출력 저장
  copy:
    content: "{{ kubeadm_init.stdout }}"
    dest: /root/kubeadm-init.log

- name: kubectl 설정 디렉토리 생성
  file:
    path: /home/seokmin/.kube
    state: directory
    owner: seokmin
    group: seokmin
    mode: '0755'

- name: admin.conf 복사 (kubectl 명령어용)
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/seokmin/.kube/config
    owner: seokmin
    group: seokmin
    mode: '0644'
    remote_src: yes

