{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: test-hybrid-back
  namespace: test
spec:
  selector:
    app: test-hybrid-back
  ports:
    - name: http
      port: {{ .Values.backend.env.PORT }}
      targetPort: {{ .Values.backend.env.PORT }}
{{- end }}