{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: test-hybrid-back-secrets
  namespace: test
type: Opaque
stringData:
  # DB 연결 정보
  POSTGRES_HOST: {{ .Values.backend.env.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.backend.env.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  # Redis 연결 정보
  REDIS_HOST: {{ .Values.backend.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.backend.env.REDIS_PORT | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  # 여기에는 AWS ESO에서 관리하지 않는 다른 시크릿들을 추가할 수 있습니다.
  # 예: JWT_SECRET, API_KEYS 등
{{- end }} 