{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-hybrid.backendFullname" . }}
  namespace: test
spec:
  selector:
    app: {{ include "test-hybrid.backendFullname" . }}
  ports:
    - name: http
      port: {{ .Values.backend.port | default 3000 }}
      targetPort: {{ .Values.backend.port | default 3000 }}
{{- end }}