global:
  domain: test.seokmin.com
  istio:
    enabled: true
    gateway: istio-system/test-gateway

frontend:
  enabled: true
  image:
    repository: harbor.seokmin.com/test/frontend
    tag: latest
  replicaCount: 2
  imagePullSecrets:
    - harbor-pull-secret
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  hpa:
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  env:
    NEXT_PUBLIC_API_URL: https://www.test.seokmin.com
#  nodeSelector:
#    kubernetes.io/hostname: onprem-worker-1



backend:
  enabled: true
  image:
    repository: harbor.seokmin.com/test/backend
    tag: latest
  port: 3000
  replicaCount: 3
  imagePullSecrets:
    - harbor-pull-secret
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 256Mi
  hpa:
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  env:
    NODE_ENV: production
  envFrom:
    - secretRef:
        name: test-hybrid-back-secrets




postgresql-ha:
  enabled: true

  postgresql:
    existingSecret: test-hybrid-db-secrets

    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    podLabels:
      sidecar.istio.io/inject: "false"

  haproxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    podLabels:
      sidecar.istio.io/inject: "false"

  pgpool:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    podLabels:
      sidecar.istio.io/inject: "false"

  persistence:
    enabled: true
    storageClass: nfs-storage
    size: 5Gi

  nodeSelector: {}
  tolerations: []

istio:
  enabled: true


#postgresql:
#  enabled: true
#  persistence:
#    enabled: true
#    storageClassName: nfs-storage
#    accessModes:
#      - ReadWriteOnce
#    size: 5Gi
#  auth:
#    existingSecret: test-hybrid-db-secrets
#  nodeSelector:
#    kubernetes.io/hostname: onprem-master
#  tolerations:
#    - key: "node-role.kubernetes.io/control-plane"
#      operator: "Exists"
#      effect: "NoSchedule"
