{{- if .Values.global.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-hybrid-vs
  namespace: test
spec:
  hosts:
    - {{ .Values.global.domain }}
  gateways:
    - {{ .Values.global.istio.gateway }}
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 308
        # 2. Google OAuth 콜백 등 프론트 내부 API (Next.js에서 처리)
{{/*    - match:*/}}
{{/*        - uri:*/}}
{{/*            prefix: "/api/auth"*/}}
{{/*      route:*/}}
{{/*        - destination:*/}}
{{/*            host: test-hybrid-front.test.svc.cluster.local*/}}
{{/*            port:*/}}
{{/*              number: 80*/}}
    - match:
        - uri:
            prefix: "/api"
      corsPolicy:
        allowOrigins:
          - exact: "https://{{ .Values.global.domain }}"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
        maxAge: "24h"
      route:
        - destination:
            host: test-hybrid-back.test.svc.cluster.local         # Stable 백엔드
            port:
              number: 3000
          weight: 10
        - destination:
            host: test-hybrid-canary-back.test.svc.cluster.local    # Canary 백엔드
            port:
              number: 3000
          weight: 90

    - route:
        - destination:
            host: test-hybrid-front.test.svc.cluster.local         # Stable 프론트엔드
            port:
              number: 80
          weight: 10
        - destination:
            host: test-hybrid-canary-front.test.svc.cluster.local    # Canary 프론트엔드
            port:
              number: 80
          weight: 90

{{- end }}