apiVersion: metallb.io/v1beta2  # ✅ 또는 stable
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"   # CRD보다 늦게 적용되도록 설정
spec:
  addresses:
    - 192.168.0.200/32