apiVersion: metallb.io/v1beta2
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "6"  # IPAddressPool보다 나중에 적용되도록 살짝 뒤로
spec:
  ipAddressPools:
    - default