# manifests/istio/virtualservices/grafana-virtualservice.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system
spec:
  hosts:
    - grafanat.seokmin.com
  gateways:
    - test-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 308
#      route:
#        - destination:
#            host: grafana.monitoring.svc.cluster.local
#            port:
#              number: 80

    - match:
        - port: 443
      route:
        - destination:
            host: grafana.monitoring.svc.cluster.local
            port:
              number: 443