---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-hybrid-logs-backup-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-hybrid-logs-backup
  namespace: monitoring
spec:
#  schedule: "0 * * * *"  # 매 정시마다 실행 (UTC 기준)
  schedule: "*/5 * * * *"  # 매 정시마다 실행 (UTC 기준)
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-logger
              image: alpine:latest
              command:
                - /bin/sh
                - -c
                - |
                  apk add --no-cache curl jq tzdata && {
                    # 한국 시간 기준 현재 시각 (UTC+9)
                    NOW_KST=$(date -u -d '+9 hour' +%Y-%m-%dT%H:00:00Z)
                    ONE_HOUR_AGO=$(date -u -d '+8 hour' +%Y-%m-%dT%H:00:00Z)

                    # YYYY-MM-DD 기준 폴더 이름
                    TODAY=$(date -u -d '+9 hour' +%Y-%m-%d)
                    HOUR=$(date -u -d '+9 hour' +%H)

                    echo "[INFO] 쿼리 실행: ${ONE_HOUR_AGO} ~ ${NOW_KST}"

                    mkdir -p /mnt/nfs-storage/test-hybrid-back-logs/${TODAY}

                    curl -G http://loki-loki-distributed-query-frontend.monitoring.svc.cluster.local:3100/loki/api/v1/query_range \
                      --data-urlencode 'query={app="test-hybrid-back"}' \
                      --data-urlencode start="${ONE_HOUR_AGO}" \
                      --data-urlencode end="${NOW_KST}" \
                      | jq '.' > /mnt/nfs-storage/test-hybrid-back-logs/${TODAY}/log-${HOUR}.json

                    echo "[DONE] 로그 저장 완료: log-${HOUR}.json"
                  }
              volumeMounts:
                - name: nfs
                  mountPath: /mnt/nfs-storage
          restartPolicy: OnFailure
          volumes:
            - name: nfs
              persistentVolumeClaim:
                claimName: test-hybrid-logs-backup-pvc