apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-db-backup-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs-storage/test-db-backup
    server: 192.168.56.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-db-backup-pvc
  namespace: test  # 너의 namespace로 바꿔줘
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: test-db-backup-pv
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: test
spec:
  schedule: "*/5 * * * *"  # 5분마다
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: bitnami/postgresql:15
              command:
                - /bin/bash
                - -c
                - |
                  export PGPASSWORD=$(cat /secrets/POSTGRES_PASSWORD)
                  pg_dump -U postgres -h test-hybrid-db-postgresql-ha-postgresql -d postgres > /backup/backup.sql
              volumeMounts:
                - name: backup-vol
                  mountPath: /backup
                - name: secret-vol
                  mountPath: /secrets
                  readOnly: true
              env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: test-hybrid-db-secrets
                      key: POSTGRES_USERNAME
                - name: PGDATABASE
                  value: postgres
          volumes:
            - name: backup-vol
              persistentVolumeClaim:
                claimName: test-db-backup-pvc
            - name: secret-vol
              secret:
                secretName: test-hybrid-db-secrets
          restartPolicy: OnFailure