---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-hybrid-logs-backup-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-hybrid-logs-backup
  namespace: test
spec:
  schedule: "*/5 * * * *"  # 일단 테스트용 5분마다
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-logger
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  NOW=$(date -u +%Y-%m-%d)
                  START="${NOW}T00:00:00Z"
                  END="${NOW}T23:59:59Z"
                  echo "[INFO] 쿼리 실행: ${START} ~ ${END}"

                  curl -G http://loki-loki-distributed-query-frontend.monitoring.svc.cluster.local:3100/loki/api/v1/query_range \
                    --data-urlencode 'query={app="test-hybrid-back"}' \
                    --data-urlencode start="${START}" \
                    --data-urlencode end="${END}" \
                    --data-urlencode limit=10000 \
                    | jq '.' > /mnt/nfs-storage/test-hybrid-logs/log-${NOW}.json

                  echo "[DONE] 로그 저장 완료: log-${NOW}.json"
              volumeMounts:
                - name: nfs
                  mountPath: /mnt/nfs-storage
          restartPolicy: OnFailure
          volumes:
            - name: nfs
              persistentVolumeClaim:
                claimName: test-hybrid-logs-backup-pvc