---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-hybrid-logs-backup-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-hybrid-logs-backup
  namespace: monitoring
spec:
  schedule: "*/5 * * * *"  # 테스트용. 실제 운용 시 0 0 * * * 로 변경
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-logger
              image: alpine:latest
              command:
                - /bin/sh
                - -c
                - |
                  apk add --no-cache curl jq && {
                    NOW=$(date -u +%Y-%m-%d)
                    START=$(date -u +"%Y-%m-%dT00:00:00Z")
                    END=$(date -u +"%Y-%m-%dT23:59:59Z")
                    echo "[INFO] 쿼리 실행: ${START} ~ ${END}"

                    mkdir -p /mnt/nfs-storage/test-hybrid-logs

                    curl -G http://loki-loki-distributed-query-frontend.monitoring.svc.cluster.local:3100/loki/api/v1/query_range \
                      --data-urlencode 'query={app="test-hybrid-back"}' \
                      --data-urlencode start="${START}" \
                      --data-urlencode end="${END}" \
                      --data-urlencode limit=10000 \
                      | jq 

                    echo "[DONE] 로그 저장 완료: log-${NOW}.json"
                  }
              volumeMounts:
                - name: nfs
                  mountPath: /mnt/nfs-storage
          restartPolicy: OnFailure
          volumes:
            - name: nfs
              persistentVolumeClaim:
                claimName: test-hybrid-logs-backup-pvc