{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: test-hybrid-back
spec:
  selector:
    app: test-hybrid-back
  ports:
    - port: 3000
      targetPort: 3000
{{- end }}