{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-hybrid.frontendFullname" . }}
  namespace: test
  labels:
    app: {{ include "test-hybrid.frontendFullname" . }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "test-hybrid.frontendFullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "test-hybrid.frontendFullname" . }}
        {{- if .Values.global.istio.enabled }}
        istio-injection: enabled
        {{- end }}
    spec:
      {{- if .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.frontend.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- if .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.frontend.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: test-hybrid-front
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

          # env (단일 환경변수들)
          {{- if .Values.frontend.env }}
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          # envFrom (Secret 또는 ConfigMap)
          {{- if .Values.frontend.envFrom }}
          envFrom:
            {{- toYaml .Values.frontend.envFrom | nindent 12 }}
          {{- end }}

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}