{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-hybrid.frontendFullname" . }}
  namespace: test
spec:
  selector:
    app: {{ include "test-hybrid.frontendFullname" . }}
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}